#!/bin/bash

set -e

TESTNAME=foobar

WESTON=./weston
LOGDIR="."
SERVERLOG="$LOGDIR/$TESTNAME-server.log"
OUTLOG="$LOGDIR/$TESTNAME.log"
TESTLOG="$LOGDIR/$TESTNAME.log"

BACKEND=headless-backend.so

# Test timeout of the screensaver
TIMEOUT=1

echo "Starting weston"
echo "Starting weston" > $SERVERLOG
$WESTON --backend=$BACKEND \
        --no-config \
        --use-pixman \
        --idle-time=$TIMEOUT \
        --log="$SERVERLOG" \
        &> "$OUTLOG" &
WESTON_PID=$(pidof $WESTON)

echo "Test screensaver timeout"
sleep 4
echo "ok" >> $TESTLOG

echo "Testing complete"
kill $WESTON_PID

echo "Results:"
echo "  server log:      $SERVERLOG"
echo "  server output:   $OUTLOG"
echo "  test log:        $TESTLOG"
